# Generated by Django 4.2.11 on 2024-04-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
