# Generated by Django 4.2.11 on 2024-04-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmes', '0002_avaliacao_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('bio', models.TextField()),
                ('foto', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('bio', models.TextField()),
                ('foto', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliacoes'},
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'verbose_name_plural': 'Filmes'},
        ),
        migrations.RemoveField(
            model_name='filme',
            name='atores',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.CreateModel(
            name='rel_filme_genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmes.filme')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmes.genero')),
            ],
            options={
                'verbose_name_plural': 'Relacoes filmes e generos',
            },
        ),
        migrations.CreateModel(
            name='rel_filme_ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmes.ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmes.filme')),
            ],
            options={
                'verbose_name_plural': 'Relacoes filmes e atores',
            },
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmes.diretor'),
        ),
    ]
